apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy
spec:
  containers:
    - name: nginx-proxy
      image: nginx
      volumeMounts:
      - name: vol1
        mountPath: "/usr/share/nginx/proxy"
  volumes:
    - name: vol1
      configMap:
        name: proxy-config 