apiVersion: v1
kind: Pod
metadata:
  name: task-pv-storage
spec:
  containers:
    - name: task-pv-storage
      image: nginx
      ports:
        - containerPort: 80
          name: http-server
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: myvolume
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: task-pv-claim
