apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storage
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/FGUF00101/data

