apiVersion: v1
kind: Pod
metadata:
  name: testapp
  namespace: test
  labels:
    name: mypod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "200m"
        memory: "1Gi"